.PHONY: tf.init tf.plan tf.apply

tf.init:
	@echo "Initializing redis configuration"
	terraform init

tf.plan:
	@echo "Planning redis configuration"
	terraform plan

tf.apply:
	echo "Applying redis configuration"
	terraform apply
